# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Pitstop Pal" do
pod 'AFNetworking'
pod 'Google-Maps-iOS-SDK'
end

target "Pitstop PalTests" do

end

